#!/bin/bash
# ---------------------------------------------------------------------
# optimization_report.sh
#
# Generates assembly (.s) output for every source file at -O0, -O1,
# -O2, and -O3, measures each file's size, and produces a comparison
# report (both a plain-text table for the terminal and a Markdown
# table for the presentation/report). Also reports the final linked
# binary's .text/.data/.bss size at each level via `size`.
#
# Usage:
#   ./tools/optimization_report.sh
#
# Output:
#   asm/O0/*.s, asm/O1/*.s, asm/O2/*.s, asm/O3/*.s   - generated assembly
#   optimization_report.md                            - the report
# ---------------------------------------------------------------------
set -e

cd "$(dirname "$0")/.."

SRC_FILES="src/main.c src/globals.c src/utility.c src/notification.c src/authentication.c src/persistence.c src/income.c src/expense.c src/transaction.c src/budget.c src/savings_goal.c src/dashboard.c src/reports.c src/recommendation.c src/investment.c src/category_index.c src/activity_log.c src/logger.c src/autosave.c"

LEVELS="O0 O1 O2 O3"

rm -rf asm
mkdir -p asm/O0 asm/O1 asm/O2 asm/O3

REPORT=optimization_report.md

{
  echo "# Optimization report"
  echo
  echo "Generated by \`tools/optimization_report.sh\`. Assembly size is the byte"
  echo "size of the \`.s\` file GCC emits with \`-S\` at each optimization level"
  echo "(source -> assembly, no linking). Binary size is \`text\`/\`data\`/\`bss\`"
  echo "of the fully linked \`financeapp\` executable at the same level."
  echo
  echo "## Per-file assembly size (bytes)"
  echo
  echo "| File | -O0 | -O1 | -O2 | -O3 | O0->O3 change |"
  echo "|---|---:|---:|---:|---:|---:|"
} > "$REPORT"

TOTAL_O0=0
TOTAL_O1=0
TOTAL_O2=0
TOTAL_O3=0

for f in $SRC_FILES; do
  base=$(basename "$f" .c)
  row="| $f "
  declare -A sizes
  for lvl in $LEVELS; do
    gcc -"$lvl" -Wall -Wextra -Iinclude -S "$f" -o "asm/$lvl/$base.s"
    sz=$(wc -c < "asm/$lvl/$base.s")
    sizes[$lvl]=$sz
    row="$row| $sz "
  done
  TOTAL_O0=$((TOTAL_O0 + sizes[O0]))
  TOTAL_O1=$((TOTAL_O1 + sizes[O1]))
  TOTAL_O2=$((TOTAL_O2 + sizes[O2]))
  TOTAL_O3=$((TOTAL_O3 + sizes[O3]))
  if [ "${sizes[O0]}" -gt 0 ]; then
    pct=$(( (sizes[O3] - sizes[O0]) * 100 / sizes[O0] ))
  else
    pct=0
  fi
  row="$row| ${pct}% |"
  echo "$row" >> "$REPORT"
  unset sizes
done

pct_total=$(( (TOTAL_O3 - TOTAL_O0) * 100 / TOTAL_O0 ))
{
  echo "| **Total** | **$TOTAL_O0** | **$TOTAL_O1** | **$TOTAL_O2** | **$TOTAL_O3** | **${pct_total}%** |"
  echo
  echo "## Linked binary size (bytes) — \`size\` text/data/bss"
  echo
  echo "| Level | text | data | bss | total |"
  echo "|---|---:|---:|---:|---:|"
} >> "$REPORT"

for lvl in $LEVELS; do
  gcc -"$lvl" -Wall -Wextra -Iinclude -pthread $SRC_FILES -o "financeapp_$lvl"
  read -r t d b dec _ <<< "$(size financeapp_"$lvl" | tail -1)"
  echo "| -$lvl | $t | $d | $b | $dec |" >> "$REPORT"
  rm -f "financeapp_$lvl"
done

echo >> "$REPORT"
echo "Assembly files are kept under \`asm/O0\` .. \`asm/O3\` for inspection." >> "$REPORT"

echo "Report written to $REPORT"
cat "$REPORT"
